name: SampleSolution
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pytorch=1.9
  - cpuonly
  - torchvision=0.10
  
  - matplotlib
  - numpy
  - pillow>=8.1.2
  - pyyaml
  - scipy
  - tensorboard
  - tqdm

  - wandb
  - seaborn
  - pandas
  - easydict

  - scikit-learn
  - prettytable
  - gdown
  - progressbar2
  - einops
  - timm

  - pip:
    - opencv-contrib-python-headless>=4.1.2
    - hexhamming==1.1
    - apex